/* Generated by meShaderEd */

#define DISPLACEMENT_SHADER displ
displacement displ (
)
{
point displ_P = point(0.000,0.000,0.000);
normal displ_N = normal(0.000,1.000,0.000);

	  P = displ_P; 
	  N = displ_N;
	
}
