/* Generated by meShaderEd */

#define DISPLACEMENT_SHADER displace01
displacement displace01 (
)
{
point displace01_P = point(0.000,0.000,0.000);
normal displace01_N = normal(0.000,1.000,0.000);

	  P = displace01_P; 
	  N = displace01_N;
	
}
