/* Generated by meShaderEd */

#define DISPLACEMENT_SHADER displacement
displacement displacement (
)
{
point displacement_P = point(0.000,0.000,0.000);
normal displacement_N = normal(0.000,1.000,0.000);

	  P = displacement_P; 
	  N = displacement_N;
	
}
