# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\ui_nodeEditor.ui'
#
# Created: Mon Aug 13 00:42:26 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NodeEditor(object):
    def setupUi(self, NodeEditor):
        NodeEditor.setObjectName(_fromUtf8("NodeEditor"))
        NodeEditor.resize(448, 498)
        self.verticalLayout = QtGui.QVBoxLayout(NodeEditor)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.name_label = QtGui.QLabel(NodeEditor)
        self.name_label.setMinimumSize(QtCore.QSize(100, 0))
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.horizontalLayout_2.addWidget(self.name_label)
        self.name_lineEdit = QtGui.QLineEdit(NodeEditor)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.horizontalLayout_2.addWidget(self.name_lineEdit)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_label = QtGui.QLabel(NodeEditor)
        self.label_label.setMinimumSize(QtCore.QSize(100, 0))
        self.label_label.setObjectName(_fromUtf8("label_label"))
        self.horizontalLayout_3.addWidget(self.label_label)
        self.label_lineEdit = QtGui.QLineEdit(NodeEditor)
        self.label_lineEdit.setObjectName(_fromUtf8("label_lineEdit"))
        self.horizontalLayout_3.addWidget(self.label_lineEdit)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.type_label = QtGui.QLabel(NodeEditor)
        self.type_label.setMinimumSize(QtCore.QSize(100, 0))
        self.type_label.setObjectName(_fromUtf8("type_label"))
        self.horizontalLayout_7.addWidget(self.type_label)
        self.type_comboBox = QtGui.QComboBox(NodeEditor)
        self.type_comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.type_comboBox.setObjectName(_fromUtf8("type_comboBox"))
        self.horizontalLayout_7.addWidget(self.type_comboBox)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.author_label = QtGui.QLabel(NodeEditor)
        self.author_label.setMinimumSize(QtCore.QSize(100, 0))
        self.author_label.setObjectName(_fromUtf8("author_label"))
        self.horizontalLayout_5.addWidget(self.author_label)
        self.author_lineEdit = QtGui.QLineEdit(NodeEditor)
        self.author_lineEdit.setObjectName(_fromUtf8("author_lineEdit"))
        self.horizontalLayout_5.addWidget(self.author_lineEdit)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.icon_label = QtGui.QLabel(NodeEditor)
        self.icon_label.setMinimumSize(QtCore.QSize(100, 0))
        self.icon_label.setObjectName(_fromUtf8("icon_label"))
        self.horizontalLayout_6.addWidget(self.icon_label)
        self.icon_lineEdit = QtGui.QLineEdit(NodeEditor)
        self.icon_lineEdit.setObjectName(_fromUtf8("icon_lineEdit"))
        self.horizontalLayout_6.addWidget(self.icon_lineEdit)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.master_label = QtGui.QLabel(NodeEditor)
        self.master_label.setMinimumSize(QtCore.QSize(100, 0))
        self.master_label.setObjectName(_fromUtf8("master_label"))
        self.horizontalLayout_8.addWidget(self.master_label)
        self.master_lineEdit = QtGui.QLineEdit(NodeEditor)
        self.master_lineEdit.setObjectName(_fromUtf8("master_lineEdit"))
        self.horizontalLayout_8.addWidget(self.master_lineEdit)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.id_label = QtGui.QLabel(NodeEditor)
        self.id_label.setEnabled(False)
        self.id_label.setMinimumSize(QtCore.QSize(100, 0))
        self.id_label.setObjectName(_fromUtf8("id_label"))
        self.horizontalLayout_9.addWidget(self.id_label)
        self.id_lineEdit = QtGui.QLineEdit(NodeEditor)
        self.id_lineEdit.setEnabled(False)
        self.id_lineEdit.setMinimumSize(QtCore.QSize(60, 0))
        self.id_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.id_lineEdit.setObjectName(_fromUtf8("id_lineEdit"))
        self.horizontalLayout_9.addWidget(self.id_lineEdit)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(20, 109, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.help_label = QtGui.QLabel(NodeEditor)
        self.help_label.setMinimumSize(QtCore.QSize(100, 0))
        self.help_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.help_label.setObjectName(_fromUtf8("help_label"))
        self.horizontalLayout_4.addWidget(self.help_label)
        self.help_plainTextEdit = QtGui.QPlainTextEdit(NodeEditor)
        self.help_plainTextEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.help_plainTextEdit.setObjectName(_fromUtf8("help_plainTextEdit"))
        self.horizontalLayout_4.addWidget(self.help_plainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(NodeEditor)
        QtCore.QMetaObject.connectSlotsByName(NodeEditor)

    def retranslateUi(self, NodeEditor):
        NodeEditor.setWindowTitle(QtGui.QApplication.translate("NodeEditor", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label.setText(QtGui.QApplication.translate("NodeEditor", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_label.setText(QtGui.QApplication.translate("NodeEditor", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.type_label.setText(QtGui.QApplication.translate("NodeEditor", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.author_label.setText(QtGui.QApplication.translate("NodeEditor", "Author", None, QtGui.QApplication.UnicodeUTF8))
        self.icon_label.setText(QtGui.QApplication.translate("NodeEditor", "Icon", None, QtGui.QApplication.UnicodeUTF8))
        self.master_label.setText(QtGui.QApplication.translate("NodeEditor", "Master", None, QtGui.QApplication.UnicodeUTF8))
        self.id_label.setText(QtGui.QApplication.translate("NodeEditor", "Node ID", None, QtGui.QApplication.UnicodeUTF8))
        self.help_label.setText(QtGui.QApplication.translate("NodeEditor", "Description", None, QtGui.QApplication.UnicodeUTF8))

