# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui_nodeEditorPanel.ui'
#
# Created: Thu Oct 11 19:06:31 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NodeEditorPanel(object):
    def setupUi(self, NodeEditorPanel):
        NodeEditorPanel.setObjectName(_fromUtf8("NodeEditorPanel"))
        NodeEditorPanel.resize(530, 552)
        self.verticalLayout_6 = QtGui.QVBoxLayout(NodeEditorPanel)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setMargin(4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.splitter = QtGui.QSplitter(NodeEditorPanel)
        self.splitter.setFrameShape(QtGui.QFrame.Panel)
        self.splitter.setFrameShadow(QtGui.QFrame.Sunken)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(8)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.toolBox = QtGui.QToolBox(self.splitter)
        self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.toolBox.setBaseSize(QtCore.QSize(200, 0))
        self.toolBox.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox.setFrameShadow(QtGui.QFrame.Plain)
        self.toolBox.setLineWidth(1)
        self.toolBox.setMidLineWidth(0)
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.node = QtGui.QWidget()
        self.node.setGeometry(QtCore.QRect(0, 0, 461, 436))
        self.node.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.node.setObjectName(_fromUtf8("node"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.node)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.nodes_listWidget = QtGui.QListWidget(self.node)
        self.nodes_listWidget.setObjectName(_fromUtf8("nodes_listWidget"))
        self.verticalLayout_7.addWidget(self.nodes_listWidget)
        self.toolBox.addItem(self.node, _fromUtf8(""))
        self.parameters = QtGui.QWidget()
        self.parameters.setGeometry(QtCore.QRect(0, 0, 461, 436))
        self.parameters.setObjectName(_fromUtf8("parameters"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.parameters)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabs_param_list = QtGui.QTabWidget(self.parameters)
        self.tabs_param_list.setObjectName(_fromUtf8("tabs_param_list"))
        self.inputs_tab = QtGui.QWidget()
        self.inputs_tab.setObjectName(_fromUtf8("inputs_tab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.inputs_tab)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.input_list = NodeNamesEditor(self.inputs_tab)
        self.input_list.setObjectName(_fromUtf8("input_list"))
        self.gridLayout_2.addWidget(self.input_list, 0, 0, 1, 1)
        self.tabs_param_list.addTab(self.inputs_tab, _fromUtf8(""))
        self.outputs_tab = QtGui.QWidget()
        self.outputs_tab.setObjectName(_fromUtf8("outputs_tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.outputs_tab)
        self.gridLayout_3.setMargin(2)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.output_list = NodeNamesEditor(self.outputs_tab)
        self.output_list.setObjectName(_fromUtf8("output_list"))
        self.gridLayout_3.addWidget(self.output_list, 0, 0, 1, 1)
        self.tabs_param_list.addTab(self.outputs_tab, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabs_param_list)
        self.toolBox.addItem(self.parameters, _fromUtf8(""))
        self.code = QtGui.QWidget()
        self.code.setGeometry(QtCore.QRect(0, 0, 461, 436))
        self.code.setObjectName(_fromUtf8("code"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.code)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabs_code_list = QtGui.QTabWidget(self.code)
        self.tabs_code_list.setObjectName(_fromUtf8("tabs_code_list"))
        self.internals_tab = QtGui.QWidget()
        self.internals_tab.setObjectName(_fromUtf8("internals_tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.internals_tab)
        self.gridLayout_4.setMargin(2)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.internals_list = NodeNamesEditor(self.internals_tab)
        self.internals_list.setObjectName(_fromUtf8("internals_list"))
        self.gridLayout_4.addWidget(self.internals_list, 0, 0, 1, 1)
        self.tabs_code_list.addTab(self.internals_tab, _fromUtf8(""))
        self.includes_tab = QtGui.QWidget()
        self.includes_tab.setObjectName(_fromUtf8("includes_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.includes_tab)
        self.gridLayout_5.setMargin(2)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.includes_list = NodeNamesEditor(self.includes_tab)
        self.includes_list.setObjectName(_fromUtf8("includes_list"))
        self.gridLayout_5.addWidget(self.includes_list, 0, 0, 1, 1)
        self.tabs_code_list.addTab(self.includes_tab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabs_code_list)
        self.toolBox.addItem(self.code, _fromUtf8(""))
        self.frame = QtGui.QFrame(self.splitter)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setMargin(2)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.side_stackedWidget = QtGui.QStackedWidget(self.frame)
        self.side_stackedWidget.setObjectName(_fromUtf8("side_stackedWidget"))
        self.side_stackedWidgetPage1 = QtGui.QWidget()
        self.side_stackedWidgetPage1.setObjectName(_fromUtf8("side_stackedWidgetPage1"))
        self.side_stackedWidget.addWidget(self.side_stackedWidgetPage1)
        self.gridLayout.addWidget(self.side_stackedWidget, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.splitter)
        self.buttonBox = QtGui.QDialogButtonBox(NodeEditorPanel)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Save)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_6.addWidget(self.buttonBox)

        self.retranslateUi(NodeEditorPanel)
        self.toolBox.setCurrentIndex(2)
        self.toolBox.layout().setSpacing(2)
        self.tabs_param_list.setCurrentIndex(0)
        self.tabs_code_list.setCurrentIndex(0)
        QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), NodeEditorPanel.onToolBoxIndexChanged)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), NodeEditorPanel.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), NodeEditorPanel.reject)
        QtCore.QMetaObject.connectSlotsByName(NodeEditorPanel)

    def retranslateUi(self, NodeEditorPanel):
        NodeEditorPanel.setWindowTitle(QtGui.QApplication.translate("NodeEditorPanel", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.node), QtGui.QApplication.translate("NodeEditorPanel", "Node", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_param_list.setTabText(self.tabs_param_list.indexOf(self.inputs_tab), QtGui.QApplication.translate("NodeEditorPanel", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_param_list.setTabText(self.tabs_param_list.indexOf(self.outputs_tab), QtGui.QApplication.translate("NodeEditorPanel", "Output", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.parameters), QtGui.QApplication.translate("NodeEditorPanel", "Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_code_list.setTabText(self.tabs_code_list.indexOf(self.internals_tab), QtGui.QApplication.translate("NodeEditorPanel", "Local variables", None, QtGui.QApplication.UnicodeUTF8))
        self.tabs_code_list.setTabText(self.tabs_code_list.indexOf(self.includes_tab), QtGui.QApplication.translate("NodeEditorPanel", "Includes", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.code), QtGui.QApplication.translate("NodeEditorPanel", "Code", None, QtGui.QApplication.UnicodeUTF8))

from nodeNamesEditor import NodeNamesEditor
