# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\ui_nodeParamEditor.ui'
#
# Created: Sun Aug 12 18:46:03 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NodeParamEditor(object):
    def setupUi(self, NodeParamEditor):
        NodeParamEditor.setObjectName(_fromUtf8("NodeParamEditor"))
        NodeParamEditor.resize(683, 390)
        self.verticalLayout = QtGui.QVBoxLayout(NodeParamEditor)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.addButton = QtGui.QPushButton(NodeParamEditor)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.horizontalLayout.addWidget(self.addButton)
        self.removeButton = QtGui.QPushButton(NodeParamEditor)
        self.removeButton.setObjectName(_fromUtf8("removeButton"))
        self.horizontalLayout.addWidget(self.removeButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.name_label = QtGui.QLabel(NodeParamEditor)
        self.name_label.setMinimumSize(QtCore.QSize(100, 0))
        self.name_label.setObjectName(_fromUtf8("name_label"))
        self.horizontalLayout_2.addWidget(self.name_label)
        self.name_lineEdit = QtGui.QLineEdit(NodeParamEditor)
        self.name_lineEdit.setObjectName(_fromUtf8("name_lineEdit"))
        self.horizontalLayout_2.addWidget(self.name_lineEdit)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.name_label_2 = QtGui.QLabel(NodeParamEditor)
        self.name_label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.name_label_2.setObjectName(_fromUtf8("name_label_2"))
        self.horizontalLayout_3.addWidget(self.name_label_2)
        self.name_lineEdit_2 = QtGui.QLineEdit(NodeParamEditor)
        self.name_lineEdit_2.setObjectName(_fromUtf8("name_lineEdit_2"))
        self.horizontalLayout_3.addWidget(self.name_lineEdit_2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(NodeParamEditor)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.check_display = QtGui.QCheckBox(NodeParamEditor)
        self.check_display.setText(_fromUtf8(""))
        self.check_display.setObjectName(_fromUtf8("check_display"))
        self.horizontalLayout_5.addWidget(self.check_display)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_3 = QtGui.QLabel(NodeParamEditor)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_6.addWidget(self.label_3)
        self.check_shader = QtGui.QCheckBox(NodeParamEditor)
        self.check_shader.setText(_fromUtf8(""))
        self.check_shader.setObjectName(_fromUtf8("check_shader"))
        self.horizontalLayout_6.addWidget(self.check_shader)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(NodeParamEditor)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.comboBox = QtGui.QComboBox(NodeParamEditor)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_7.addWidget(self.comboBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_5 = QtGui.QLabel(NodeParamEditor)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.comboBox_2 = QtGui.QComboBox(NodeParamEditor)
        self.comboBox_2.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_8.addWidget(self.comboBox_2)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_6 = QtGui.QLabel(NodeParamEditor)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_9.addWidget(self.label_6)
        self.comboBox_3 = QtGui.QComboBox(NodeParamEditor)
        self.comboBox_3.setMinimumSize(QtCore.QSize(100, 0))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_9.addWidget(self.comboBox_3)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.name_label_3 = QtGui.QLabel(NodeParamEditor)
        self.name_label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.name_label_3.setObjectName(_fromUtf8("name_label_3"))
        self.horizontalLayout_10.addWidget(self.name_label_3)
        self.name_lineEdit_3 = QtGui.QLineEdit(NodeParamEditor)
        self.name_lineEdit_3.setObjectName(_fromUtf8("name_lineEdit_3"))
        self.horizontalLayout_10.addWidget(self.name_lineEdit_3)
        self.horizontalLayout_10.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.value_widget = QtGui.QWidget(NodeParamEditor)
        self.value_widget.setObjectName(_fromUtf8("value_widget"))
        self.verticalLayout.addWidget(self.value_widget)
        self.def_value_widget_2 = QtGui.QWidget(NodeParamEditor)
        self.def_value_widget_2.setObjectName(_fromUtf8("def_value_widget_2"))
        self.verticalLayout.addWidget(self.def_value_widget_2)
        spacerItem6 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(NodeParamEditor)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.plainTextEdit = QtGui.QPlainTextEdit(NodeParamEditor)
        self.plainTextEdit.setMinimumSize(QtCore.QSize(0, 60))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.horizontalLayout_4.addWidget(self.plainTextEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(NodeParamEditor)
        QtCore.QObject.connect(self.addButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NodeParamEditor.onAddItem)
        QtCore.QObject.connect(self.removeButton, QtCore.SIGNAL(_fromUtf8("clicked()")), NodeParamEditor.onRemoveItem)
        QtCore.QMetaObject.connectSlotsByName(NodeParamEditor)

    def retranslateUi(self, NodeParamEditor):
        NodeParamEditor.setWindowTitle(QtGui.QApplication.translate("NodeParamEditor", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("NodeParamEditor", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.removeButton.setText(QtGui.QApplication.translate("NodeParamEditor", "Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label.setText(QtGui.QApplication.translate("NodeParamEditor", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label_2.setText(QtGui.QApplication.translate("NodeParamEditor", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("NodeParamEditor", "Display", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("NodeParamEditor", "Shader Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("NodeParamEditor", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("NodeParamEditor", "Detail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("NodeParamEditor", "GUI Subtype", None, QtGui.QApplication.UnicodeUTF8))
        self.name_label_3.setText(QtGui.QApplication.translate("NodeParamEditor", "Range", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("NodeParamEditor", "Description", None, QtGui.QApplication.UnicodeUTF8))

