# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\ui_settingsSetup.ui'
#
# Created: Wed Jul 18 14:26:06 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SettingsSetup(object):
    def setupUi(self, SettingsSetup):
        SettingsSetup.setObjectName(_fromUtf8("SettingsSetup"))
        SettingsSetup.resize(376, 346)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsSetup.sizePolicy().hasHeightForWidth())
        SettingsSetup.setSizePolicy(sizePolicy)
        SettingsSetup.setMinimumSize(QtCore.QSize(0, 0))
        SettingsSetup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        SettingsSetup.setSizeGripEnabled(False)
        self.verticalLayout_2 = QtGui.QVBoxLayout(SettingsSetup)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.grp_dirs = QtGui.QGroupBox(SettingsSetup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.grp_dirs.sizePolicy().hasHeightForWidth())
        self.grp_dirs.setSizePolicy(sizePolicy)
        self.grp_dirs.setMinimumSize(QtCore.QSize(0, 0))
        self.grp_dirs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.grp_dirs.setObjectName(_fromUtf8("grp_dirs"))
        self.verticalLayout = QtGui.QVBoxLayout(self.grp_dirs)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.hl_temp = QtGui.QHBoxLayout()
        self.hl_temp.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.hl_temp.setObjectName(_fromUtf8("hl_temp"))
        self.label_temp = QtGui.QLabel(self.grp_dirs)
        self.label_temp.setMinimumSize(QtCore.QSize(80, 0))
        self.label_temp.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_temp.setBaseSize(QtCore.QSize(60, 0))
        self.label_temp.setObjectName(_fromUtf8("label_temp"))
        self.hl_temp.addWidget(self.label_temp)
        self.lineEdit_temp = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_temp.setObjectName(_fromUtf8("lineEdit_temp"))
        self.hl_temp.addWidget(self.lineEdit_temp)
        self.btn_temp_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_temp_dir.setObjectName(_fromUtf8("btn_temp_dir"))
        self.hl_temp.addWidget(self.btn_temp_dir)
        self.hl_temp.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_temp)
        self.hl_inc = QtGui.QHBoxLayout()
        self.hl_inc.setObjectName(_fromUtf8("hl_inc"))
        self.label_inc = QtGui.QLabel(self.grp_dirs)
        self.label_inc.setMinimumSize(QtCore.QSize(80, 0))
        self.label_inc.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_inc.setObjectName(_fromUtf8("label_inc"))
        self.hl_inc.addWidget(self.label_inc)
        self.lineEdit_inc = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_inc.setObjectName(_fromUtf8("lineEdit_inc"))
        self.hl_inc.addWidget(self.lineEdit_inc)
        self.btn_inc_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_inc_dir.setObjectName(_fromUtf8("btn_inc_dir"))
        self.hl_inc.addWidget(self.btn_inc_dir)
        self.hl_inc.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_inc)
        self.hl_lib = QtGui.QHBoxLayout()
        self.hl_lib.setObjectName(_fromUtf8("hl_lib"))
        self.label_lib = QtGui.QLabel(self.grp_dirs)
        self.label_lib.setMinimumSize(QtCore.QSize(80, 0))
        self.label_lib.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_lib.setObjectName(_fromUtf8("label_lib"))
        self.hl_lib.addWidget(self.label_lib)
        self.lineEdit_lib = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_lib.setObjectName(_fromUtf8("lineEdit_lib"))
        self.hl_lib.addWidget(self.lineEdit_lib)
        self.btn_lib_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_lib_dir.setObjectName(_fromUtf8("btn_lib_dir"))
        self.hl_lib.addWidget(self.btn_lib_dir)
        self.hl_lib.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_lib)
        self.hl_nodes = QtGui.QHBoxLayout()
        self.hl_nodes.setObjectName(_fromUtf8("hl_nodes"))
        self.label_nodes = QtGui.QLabel(self.grp_dirs)
        self.label_nodes.setMinimumSize(QtCore.QSize(80, 0))
        self.label_nodes.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_nodes.setObjectName(_fromUtf8("label_nodes"))
        self.hl_nodes.addWidget(self.label_nodes)
        self.lineEdit_nodes = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_nodes.setObjectName(_fromUtf8("lineEdit_nodes"))
        self.hl_nodes.addWidget(self.lineEdit_nodes)
        self.btn_nodes_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_nodes_dir.setObjectName(_fromUtf8("btn_nodes_dir"))
        self.hl_nodes.addWidget(self.btn_nodes_dir)
        self.hl_nodes.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_nodes)
        self.hl_shaders = QtGui.QHBoxLayout()
        self.hl_shaders.setObjectName(_fromUtf8("hl_shaders"))
        self.label_shaders = QtGui.QLabel(self.grp_dirs)
        self.label_shaders.setMinimumSize(QtCore.QSize(80, 0))
        self.label_shaders.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_shaders.setObjectName(_fromUtf8("label_shaders"))
        self.hl_shaders.addWidget(self.label_shaders)
        self.lineEdit_shaders = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_shaders.setObjectName(_fromUtf8("lineEdit_shaders"))
        self.hl_shaders.addWidget(self.lineEdit_shaders)
        self.btn_shaders_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_shaders_dir.setObjectName(_fromUtf8("btn_shaders_dir"))
        self.hl_shaders.addWidget(self.btn_shaders_dir)
        self.hl_shaders.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_shaders)
        self.hl_textures = QtGui.QHBoxLayout()
        self.hl_textures.setObjectName(_fromUtf8("hl_textures"))
        self.label_textures = QtGui.QLabel(self.grp_dirs)
        self.label_textures.setMinimumSize(QtCore.QSize(80, 0))
        self.label_textures.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_textures.setObjectName(_fromUtf8("label_textures"))
        self.hl_textures.addWidget(self.label_textures)
        self.lineEdit_textures = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_textures.setObjectName(_fromUtf8("lineEdit_textures"))
        self.hl_textures.addWidget(self.lineEdit_textures)
        self.btn_textures_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_textures_dir.setObjectName(_fromUtf8("btn_textures_dir"))
        self.hl_textures.addWidget(self.btn_textures_dir)
        self.hl_textures.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_textures)
        self.hl_archives = QtGui.QHBoxLayout()
        self.hl_archives.setObjectName(_fromUtf8("hl_archives"))
        self.label_archives = QtGui.QLabel(self.grp_dirs)
        self.label_archives.setMinimumSize(QtCore.QSize(80, 0))
        self.label_archives.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_archives.setObjectName(_fromUtf8("label_archives"))
        self.hl_archives.addWidget(self.label_archives)
        self.lineEdit_archives = QtGui.QLineEdit(self.grp_dirs)
        self.lineEdit_archives.setObjectName(_fromUtf8("lineEdit_archives"))
        self.hl_archives.addWidget(self.lineEdit_archives)
        self.btn_archives_dir = QtGui.QToolButton(self.grp_dirs)
        self.btn_archives_dir.setObjectName(_fromUtf8("btn_archives_dir"))
        self.hl_archives.addWidget(self.btn_archives_dir)
        self.hl_archives.setStretch(1, 1)
        self.verticalLayout.addLayout(self.hl_archives)
        self.verticalLayout_2.addWidget(self.grp_dirs)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.buttonBox = QtGui.QDialogButtonBox(SettingsSetup)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(SettingsSetup)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), SettingsSetup.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), SettingsSetup.reject)
        QtCore.QObject.connect(self.btn_lib_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseLibraryDir)
        QtCore.QObject.connect(self.btn_temp_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseTempDir)
        QtCore.QObject.connect(self.btn_inc_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseIncludesDir)
        QtCore.QObject.connect(self.btn_nodes_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseNodesDir)
        QtCore.QObject.connect(self.btn_shaders_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseShadersDir)
        QtCore.QObject.connect(self.btn_textures_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseTexturesDir)
        QtCore.QObject.connect(self.btn_archives_dir, QtCore.SIGNAL(_fromUtf8("clicked()")), SettingsSetup.onBrowseArchivesDir)
        QtCore.QMetaObject.connectSlotsByName(SettingsSetup)

    def retranslateUi(self, SettingsSetup):
        SettingsSetup.setWindowTitle(QtGui.QApplication.translate("SettingsSetup", "Settings Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.grp_dirs.setTitle(QtGui.QApplication.translate("SettingsSetup", "Directories", None, QtGui.QApplication.UnicodeUTF8))
        self.label_temp.setText(QtGui.QApplication.translate("SettingsSetup", "Temp", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_temp_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_inc.setText(QtGui.QApplication.translate("SettingsSetup", "Includes", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_inc_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_lib.setText(QtGui.QApplication.translate("SettingsSetup", "Library", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_lib_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nodes.setText(QtGui.QApplication.translate("SettingsSetup", "Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_nodes_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_shaders.setText(QtGui.QApplication.translate("SettingsSetup", "Shaders", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_shaders_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_textures.setText(QtGui.QApplication.translate("SettingsSetup", "Textures", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_textures_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_archives.setText(QtGui.QApplication.translate("SettingsSetup", "Archives", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_archives_dir.setText(QtGui.QApplication.translate("SettingsSetup", "...", None, QtGui.QApplication.UnicodeUTF8))

