# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/nodeEditor\ui_NodeEditorDialog.ui'
#
# Created: Thu Oct 17 14:57:09 2013
#      by: PyQt4 UI code generator 4.10.2-snapshot-a8a14dd99d1e
#
# WARNING! All changes made in this file will be lost!

from core.mePyQt import QtCore, QtGui

if QtCore.QT_VERSION < 50000 :
	QtModule = QtGui
else :
	from core.mePyQt import QtWidgets
	QtModule = QtWidgets

try:
		_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
		def _fromUtf8(s):
				return s

try:
		_encoding = QtGui.QApplication.UnicodeUTF8
		def _translate(context, text, disambig):
				return QtModule.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
		def _translate(context, text, disambig):
				return QtModule.QApplication.translate(context, text, disambig)

class Ui_NodeEditorDialog(object):
		def setupUi(self, NodeEditorDialog):
				NodeEditorDialog.setObjectName(_fromUtf8("NodeEditorDialog"))
				NodeEditorDialog.resize(750, 658)
				self.verticalLayout = QtModule.QVBoxLayout(NodeEditorDialog)
				self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
				self.splitter = QtModule.QSplitter(NodeEditorDialog)
				self.splitter.setLineWidth(2)
				self.splitter.setOrientation(QtCore.Qt.Horizontal)
				self.splitter.setHandleWidth(8)
				self.splitter.setChildrenCollapsible(False)
				self.splitter.setObjectName(_fromUtf8("splitter"))
				self.toolBox = QtModule.QToolBox(self.splitter)
				self.toolBox.setMinimumSize(QtCore.QSize(0, 0))
				self.toolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
				self.toolBox.setBaseSize(QtCore.QSize(200, 0))
				self.toolBox.setFrameShape(QtModule.QFrame.NoFrame)
				self.toolBox.setFrameShadow(QtModule.QFrame.Plain)
				self.toolBox.setLineWidth(1)
				self.toolBox.setMidLineWidth(0)
				self.toolBox.setObjectName(_fromUtf8("toolBox"))
				self.internals = QtModule.QWidget()
				self.internals.setGeometry(QtCore.QRect(0, 0, 204, 501))
				self.internals.setObjectName(_fromUtf8("internals"))
				self.verticalLayout_3 = QtModule.QVBoxLayout(self.internals)
				self.verticalLayout_3.setSpacing(0)
				if QtCore.QT_VERSION < 50000 :
					self.verticalLayout_3.setMargin(0)
				self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
				self.tabs_code_list = QtModule.QTabWidget(self.internals)
				self.tabs_code_list.setObjectName(_fromUtf8("tabs_code_list"))
				self.internals_tab = QtModule.QWidget()
				self.internals_tab.setObjectName(_fromUtf8("internals_tab"))
				self.gridLayout_4 = QtModule.QGridLayout(self.internals_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_4.setMargin(2)
				self.gridLayout_4.setSpacing(0)
				self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
				self.internals_list = NodeNamesEditor(self.internals_tab)
				self.internals_list.setObjectName(_fromUtf8("internals_list"))
				self.gridLayout_4.addWidget(self.internals_list, 0, 0, 1, 1)
				self.tabs_code_list.addTab(self.internals_tab, _fromUtf8(""))
				self.includes_tab = QtModule.QWidget()
				self.includes_tab.setObjectName(_fromUtf8("includes_tab"))
				self.gridLayout_5 = QtModule.QGridLayout(self.includes_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_5.setMargin(2)
				self.gridLayout_5.setSpacing(0)
				self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
				self.includes_list = NodeNamesEditor(self.includes_tab)
				self.includes_list.setObjectName(_fromUtf8("includes_list"))
				self.gridLayout_5.addWidget(self.includes_list, 0, 0, 1, 1)
				self.tabs_code_list.addTab(self.includes_tab, _fromUtf8(""))
				self.verticalLayout_3.addWidget(self.tabs_code_list)
				self.toolBox.addItem(self.internals, _fromUtf8(""))
				self.parameters = QtModule.QWidget()
				self.parameters.setGeometry(QtCore.QRect(0, 0, 204, 501))
				self.parameters.setObjectName(_fromUtf8("parameters"))
				self.verticalLayout_8 = QtModule.QVBoxLayout(self.parameters)
				self.verticalLayout_8.setSpacing(0)
				if QtCore.QT_VERSION < 50000 :
					self.verticalLayout_8.setMargin(0)
				self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
				self.tabs_param_list = QtModule.QTabWidget(self.parameters)
				self.tabs_param_list.setObjectName(_fromUtf8("tabs_param_list"))
				self.inputs_tab = QtModule.QWidget()
				self.inputs_tab.setObjectName(_fromUtf8("inputs_tab"))
				self.gridLayout_2 = QtModule.QGridLayout(self.inputs_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_2.setMargin(2)
				self.gridLayout_2.setSpacing(0)
				self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
				self.input_list = NodeNamesEditor(self.inputs_tab)
				self.input_list.setObjectName(_fromUtf8("input_list"))
				self.gridLayout_2.addWidget(self.input_list, 0, 0, 1, 1)
				self.tabs_param_list.addTab(self.inputs_tab, _fromUtf8(""))
				self.outputs_tab = QtModule.QWidget()
				self.outputs_tab.setObjectName(_fromUtf8("outputs_tab"))
				self.gridLayout_3 = QtModule.QGridLayout(self.outputs_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_3.setMargin(2)
				self.gridLayout_3.setSpacing(0)
				self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
				self.output_list = NodeNamesEditor(self.outputs_tab)
				self.output_list.setObjectName(_fromUtf8("output_list"))
				self.gridLayout_3.addWidget(self.output_list, 0, 0, 1, 1)
				self.tabs_param_list.addTab(self.outputs_tab, _fromUtf8(""))
				self.verticalLayout_8.addWidget(self.tabs_param_list)
				self.toolBox.addItem(self.parameters, _fromUtf8(""))
				self.handlers = QtModule.QWidget()
				self.handlers.setGeometry(QtCore.QRect(0, 0, 204, 501))
				self.handlers.setObjectName(_fromUtf8("handlers"))
				self.verticalLayout_2 = QtModule.QVBoxLayout(self.handlers)
				self.verticalLayout_2.setSpacing(0)
				if QtCore.QT_VERSION < 50000 :
					self.verticalLayout_2.setMargin(0)
				self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
				self.handlers_list = NodeNamesEditor(self.handlers)
				self.handlers_list.setObjectName(_fromUtf8("handlers_list"))
				self.verticalLayout_2.addWidget(self.handlers_list)
				self.toolBox.addItem(self.handlers, _fromUtf8(""))
				self.links = QtModule.QWidget()
				self.links.setGeometry(QtCore.QRect(0, 0, 204, 501))
				self.links.setObjectName(_fromUtf8("links"))
				self.verticalLayout_81 = QtModule.QVBoxLayout(self.links)
				self.verticalLayout_81.setSpacing(0)
				if QtCore.QT_VERSION < 50000 :
					self.verticalLayout_81.setMargin(0)
				self.verticalLayout_81.setObjectName(_fromUtf8("verticalLayout_81"))
				self.tabs_links_list = QtModule.QTabWidget(self.links)
				self.tabs_links_list.setObjectName(_fromUtf8("tabs_links_list"))
				self.input_links_tab = QtModule.QWidget()
				self.input_links_tab.setObjectName(_fromUtf8("input_links_tab"))
				self.gridLayout_6 = QtModule.QGridLayout(self.input_links_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_6.setMargin(2)
				self.gridLayout_6.setSpacing(0)
				self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
				self.input_links_listWidget = QtModule.QListWidget(self.input_links_tab)
				self.input_links_listWidget.setObjectName(_fromUtf8("input_links_listWidget"))
				self.gridLayout_6.addWidget(self.input_links_listWidget, 0, 0, 1, 1)
				self.tabs_links_list.addTab(self.input_links_tab, _fromUtf8(""))
				self.output_links_tab = QtModule.QWidget()
				self.output_links_tab.setObjectName(_fromUtf8("output_links_tab"))
				self.gridLayout_66 = QtModule.QGridLayout(self.output_links_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_66.setMargin(2)
				self.gridLayout_66.setSpacing(0)
				self.gridLayout_66.setObjectName(_fromUtf8("gridLayout_66"))
				self.output_links_listWidget = QtModule.QListWidget(self.output_links_tab)
				self.output_links_listWidget.setObjectName(_fromUtf8("output_links_listWidget"))
				self.gridLayout_66.addWidget(self.output_links_listWidget, 0, 0, 1, 1)
				self.tabs_links_list.addTab(self.output_links_tab, _fromUtf8(""))
				self.verticalLayout_81.addWidget(self.tabs_links_list)
				self.toolBox.addItem(self.links, _fromUtf8(""))
				self.tabWidget = QtModule.QTabWidget(self.splitter)
				self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
				self.node_tab = QtModule.QWidget()
				self.node_tab.setObjectName(_fromUtf8("node_tab"))
				self.gridLayout_10 = QtModule.QGridLayout(self.node_tab)
				self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
				self.node = NodePropertiesEditor(self.node_tab)
				self.node.setObjectName(_fromUtf8("node"))
				self.gridLayout_10.addWidget(self.node, 0, 0, 1, 1)
				self.tabWidget.addTab(self.node_tab, _fromUtf8(""))
				self.node_code_tab = QtModule.QWidget()
				self.node_code_tab.setObjectName(_fromUtf8("node_code_tab"))
				self.gridLayout = QtModule.QGridLayout(self.node_code_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout.setMargin(2)
				self.gridLayout.setSpacing(2)
				self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
				self.node_code = NodeCodeEditor(self.node_code_tab)
				self.node_code.setObjectName(_fromUtf8("node_code"))
				self.gridLayout.addWidget(self.node_code, 0, 0, 1, 1)
				self.tabWidget.addTab(self.node_code_tab, _fromUtf8(""))
				self.control_code_tab = QtModule.QWidget()
				self.control_code_tab.setObjectName(_fromUtf8("control_code_tab"))
				self.gridLayout_7 = QtModule.QGridLayout(self.control_code_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_7.setMargin(2)
				self.gridLayout_7.setSpacing(2)
				self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
				self.control_code = NodeCodeEditor(self.control_code_tab)
				self.control_code.setObjectName(_fromUtf8("control_code"))
				self.gridLayout_7.addWidget(self.control_code, 0, 0, 1, 1)
				self.tabWidget.addTab(self.control_code_tab, _fromUtf8(""))
				self.event_code_tab = QtModule.QWidget()
				self.event_code_tab.setObjectName(_fromUtf8("event_code_tab"))
				self.gridLayout_8 = QtModule.QGridLayout(self.event_code_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_8.setMargin(2)
				self.gridLayout_8.setSpacing(2)
				self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
				self.event_code = NodeCodeEditor(self.event_code_tab)
				self.event_code.setObjectName(_fromUtf8("event_code"))
				self.gridLayout_8.addWidget(self.event_code, 0, 0, 1, 1)
				self.tabWidget.addTab(self.event_code_tab, _fromUtf8(""))
				self.param_code_tab = QtModule.QWidget()
				self.param_code_tab.setObjectName(_fromUtf8("param_code_tab"))
				self.gridLayout_9 = QtModule.QGridLayout(self.param_code_tab)
				if QtCore.QT_VERSION < 50000 :
					self.gridLayout_9.setMargin(2)
				self.gridLayout_9.setSpacing(2)
				self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
				self.param_code = NodeCodeEditor(self.param_code_tab)
				self.param_code.setObjectName(_fromUtf8("param_code"))
				self.gridLayout_9.addWidget(self.param_code, 0, 0, 1, 1)
				self.tabWidget.addTab(self.param_code_tab, _fromUtf8(""))
				self.param_tab = QtModule.QWidget()
				self.param_tab.setObjectName(_fromUtf8("param_tab"))
				self.gridLayout_11 = QtModule.QGridLayout(self.param_tab)
				self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
				self.param = NodeParamEditor(self.param_tab)
				self.param.setObjectName(_fromUtf8("param"))
				self.gridLayout_11.addWidget(self.param, 0, 0, 1, 1)
				self.tabWidget.addTab(self.param_tab, _fromUtf8(""))
				self.link_tab = QtModule.QWidget()
				self.link_tab.setObjectName(_fromUtf8("link_tab"))
				self.gridLayout_12 = QtModule.QGridLayout(self.link_tab)
				self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
				self.link = NodeLinkEditor(self.link_tab)
				self.link.setObjectName(_fromUtf8("link"))
				self.gridLayout_12.addWidget(self.link, 0, 0, 1, 1)
				self.tabWidget.addTab(self.link_tab, _fromUtf8(""))
				self.verticalLayout.addWidget(self.splitter)
				self.horizontalLayout = QtModule.QHBoxLayout()
				self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
				spacerItem = QtModule.QSpacerItem(40, 20, QtModule.QSizePolicy.Expanding, QtModule.QSizePolicy.Minimum)
				self.horizontalLayout.addItem(spacerItem)
				self.btn_save = QtModule.QPushButton(NodeEditorDialog)
				self.btn_save.setObjectName(_fromUtf8("btn_save"))
				self.horizontalLayout.addWidget(self.btn_save)
				self.btn_close = QtModule.QPushButton(NodeEditorDialog)
				self.btn_close.setObjectName(_fromUtf8("btn_close"))
				self.horizontalLayout.addWidget(self.btn_close)
				self.verticalLayout.addLayout(self.horizontalLayout)
				self.verticalLayout.setStretch(0, 1)

				self.retranslateUi(NodeEditorDialog)
				self.toolBox.setCurrentIndex(0)
				self.toolBox.layout().setSpacing(6)
				self.tabs_code_list.setCurrentIndex(0)
				self.tabs_param_list.setCurrentIndex(0)
				self.tabs_links_list.setCurrentIndex(0)
				self.tabWidget.setCurrentIndex(0)
				if QtCore.QT_VERSION < 50000 :
					QtCore.QObject.connect(self.toolBox, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), NodeEditorDialog.onToolBoxIndexChanged)
					QtCore.QObject.connect(self.btn_save, QtCore.SIGNAL(_fromUtf8("clicked()")), NodeEditorDialog.accept)
					QtCore.QObject.connect(self.btn_close, QtCore.SIGNAL(_fromUtf8("clicked()")), NodeEditorDialog.reject)
					QtCore.QObject.connect(self.input_links_listWidget, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), NodeEditorDialog.updateGui)
					QtCore.QObject.connect(self.output_links_listWidget, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), NodeEditorDialog.updateGui)
					QtCore.QObject.connect(self.tabs_links_list, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), NodeEditorDialog.updateGui)
				else :
					self.toolBox.currentChanged.connect( NodeEditorDialog.onToolBoxIndexChanged)
					self.btn_save.clicked.connect( NodeEditorDialog.accept)
					self.btn_close.clicked.connect( NodeEditorDialog.reject)
					self.input_links_listWidget.itemSelectionChanged.connect( NodeEditorDialog.updateGui)
					self.output_links_listWidget.itemSelectionChanged.connect( NodeEditorDialog.updateGui)
					self.tabs_links_list.currentChanged.connect( NodeEditorDialog.updateGui)
					
				QtCore.QMetaObject.connectSlotsByName(NodeEditorDialog)

		def retranslateUi(self, NodeEditorDialog):
				NodeEditorDialog.setWindowTitle(_translate("NodeEditorDialog", "NodeEditor", None))
				self.tabs_code_list.setTabText(self.tabs_code_list.indexOf(self.internals_tab), _translate("NodeEditorDialog", "Local variables", None))
				self.tabs_code_list.setTabText(self.tabs_code_list.indexOf(self.includes_tab), _translate("NodeEditorDialog", "Includes", None))
				self.toolBox.setItemText(self.toolBox.indexOf(self.internals), _translate("NodeEditorDialog", "Internals", None))
				self.tabs_param_list.setTabText(self.tabs_param_list.indexOf(self.inputs_tab), _translate("NodeEditorDialog", "Input", None))
				self.tabs_param_list.setTabText(self.tabs_param_list.indexOf(self.outputs_tab), _translate("NodeEditorDialog", "Output", None))
				self.toolBox.setItemText(self.toolBox.indexOf(self.parameters), _translate("NodeEditorDialog", "Parameters", None))
				self.toolBox.setItemText(self.toolBox.indexOf(self.handlers), _translate("NodeEditorDialog", "Event Handlers", None))
				self.tabs_links_list.setTabText(self.tabs_links_list.indexOf(self.input_links_tab), _translate("NodeEditorDialog", "Input", None))
				self.tabs_links_list.setTabText(self.tabs_links_list.indexOf(self.output_links_tab), _translate("NodeEditorDialog", "Output", None))
				self.toolBox.setItemText(self.toolBox.indexOf(self.links), _translate("NodeEditorDialog", "Links", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.node_tab), _translate("NodeEditorDialog", "Node", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.node_code_tab), _translate("NodeEditorDialog", "Node Code", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.control_code_tab), _translate("NodeEditorDialog", "Control Code", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.event_code_tab), _translate("NodeEditorDialog", "Event Code", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.param_code_tab), _translate("NodeEditorDialog", "Param Code", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.param_tab), _translate("NodeEditorDialog", "Parameter", None))
				self.tabWidget.setTabText(self.tabWidget.indexOf(self.link_tab), _translate("NodeEditorDialog", "Link Info", None))
				self.btn_save.setText(_translate("NodeEditorDialog", "Save", None))
				self.btn_close.setText(_translate("NodeEditorDialog", "Close", None))

from nodeNamesEditor import NodeNamesEditor
from nodePropertiesEditor import NodePropertiesEditor
from nodeCodeEditor import NodeCodeEditor
from nodeParamEditor import NodeParamEditor
from nodeLinkEditor import NodeLinkEditor
